import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import { LeftSidebar, Separator } from "@/components";
import "./globals.css";

const inter = Inconsolata({ weight: "400", subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <header className="w-full h-14 flex justify-end items-center px-12"></header>
      <main className="flex px-16 h-[calc(100vh-7rem)]">
        <LeftSidebar />
        <Separator />
        <div className="container overflow-y-auto p-12">{children}</div>
      </main>

      <footer className="h-14"></footer>
    </body>
  </html>
);

export { metadata };
export default RootLayout;
