import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import { Navigation } from "@/components";
import "./globals.css";

const Separator = () => (
  <div className="h-full w-1 bg-green-500 rounded-full"></div>
);

const LeftSidebar = () => (
  <div className="flex flex-col overflow-y-auto w-96 pr-12">
    <div className="relative min-h-[208px] min-w-[208px] overflow-hidden">
      <Image
        className="scale-150 object-contain"
        alt="bio image"
        fill
        src="/my_photo.jpg"
      />
    </div>
    <h1 className="pb-10 pt-6 text-xl">Viktor Shchepliahin</h1>
    <Navigation />
  </div>
);

const inter = Inconsolata({ weight: "400", subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <header className="w-full h-14 flex justify-end items-center px-12">
        <div className="w-16 flex justify-between text-lg">
          <Link href="" className="hover:brightness-150">
            EN
          </Link>
          <Link href="" className="hover:brightness-150">
            DE
          </Link>
        </div>
      </header>
      <main className="flex px-16 h-[calc(100vh-7rem)]">
        <LeftSidebar />
        <Separator />
        <div className="container overflow-y-auto p-12">{children}</div>
      </main>

      <footer className="h-14"></footer>
    </body>
  </html>
);

export { metadata };
export default RootLayout;
